config/routes.rb
Rails.application.routes.draw do

  get 'signup',    to: 'users#new',        as: 'signup'
  get 'login',     to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :services
  resources :bookings, only: [:index, :show, :create, :new, :destroy]
  get 'about',   to: 'static_pages#about',   as: 'about'
  get 'contact', to: 'static_pages#contact', as: 'contact'

  get 'static_pages/index'
  post 'static_pages/thank_you'

  root 'static_pages#landing_page'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :service
	belongs_to :user
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :bookings

	validates :name, presence: true
	validates :description, presence: true
	validates :image_url, presence: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, presence: true, uniqueness: true
	validates :password, length: { minimum: 8 }

	has_many :bookings
	has_many :services
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	# Find user model based on the session's user_id
  	# and only do this if session user id exists.
  	# Cache above in instance variable due to likelyhood of 
  	# being called more than once
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Helper method allows us to access the current user method
  # inside the views.
  helper_method :current_user


  def authorize
    redirect_to login_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	
	def index
		@bookings = Booking.all
		@bookings_by_date = @bookings.group_by(&:date) 
		@date = params[:date] ? Date.parse(params[:date]) : Date.today
	end

	def show
		@booking = Booking.find(params[:id])
	end

	def new
		@booking = Booking.new(date: Date.today )
	end

	def create
		@booking = Booking.new(booking_params)
		if @booking.save 
			redirect_to bookings_path, :notice => "Thank You. Your appointment for #{@booking.date} has been made."
		else
			render 'new'
		end
		
	end

	def destroy
	end


	private

	def booking_params
		params.require(:booking).permit(:date, :description)
	end

	
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:edit, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
      if @service.save
         flash[:success] = 'Service was successfully created.'
         redirect_to @service  
      else
         render :new 
      end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    
      if @service.update(service_params)
        flash[:success] = 'Service was successfully updated.'
        redirect_to @service 
      else
         render :edit 
      end
    
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :image_url, :location_of_service)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id 
  		redirect_to root_path, notice: "Logged In!"
  	else
  		flash.now.alert = "Email or password is invalid"
  		render "new"
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def landing_page
  	#retrieves first service in Services table and sets it to "@featured_service" variable.
  	@featured_service = Service.first
  end

  def thank_you
  	@name = params[:name]
  	@email = params[:email]
  	@message = params[:message]
  	ActionMailer::Base.mail(:from => @email,
  				:to => 'takumab@gmail.com',
  				:subject => "A new contact form message from #{@name}.",
  				:body => @message).deliver_now

  end


  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id # Logs user in after sign up
			redirect_to root_path, notice: "Thank you for signing up!"
		else
			render 'new'
		end
	end



	private

	def user_params
		params.require(:user).permit(:email, :password_digest, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
		case level
			when 'notice' then "alert alert-info"
			when 'success' then "alert alert-success"
			when 'error' then "alert alert-error"
			when 'alert' then "alert alert-error"
		end
	end
end

app/helpers/calendar_helper.rb
module CalendarHelper
	def calendar(date = Date.today, &block)
		Calendar.new(self, date, block).table
	end

	class Calendar < Struct.new(:view, :date, :callback) # defines accessors for these various attributes
		HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
		START_DAY = :sunday

		delegate :content_tag, to: :view

		def table
			content_tag :table, class: "calendar" do 
				header + week_rows
			end
		end

		def header 
			content_tag :tr do
				HEADER.map { |day| content_tag :th, day }.join.html_safe
			end
		end

		def week_rows
			weeks.map do |week|
				content_tag :tr do
					week.map { |day| day_cell(day) }.join.html_safe
				end
			end.join.html_safe
		end

		def day_cell(day)
			content_tag :td, view.capture(day, &callback), class: day_classes(day)
		end

		def day_classes(day)
			classes = []
			classes << "today" if day == Date.today
			classes << "notmonth" if day.month != date.month
			classes.empty? ? nil : classes.join(" ")
		end

		def weeks
			first = date.beginning_of_month.beginning_of_week(START_DAY)
			last = date.end_of_month.end_of_week(START_DAY)
			(first..last).to_a.in_groups_of(7)
		end

	end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
	<% if @booking.errors.any? %>
		<div class="error_explanantion">
			<h2><%= pluralize(@booking.errors.count, "error") %> prohibited this user from being saved.</h2>
			<ul>
				<% @booking.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :date %> <br>
		<%= f.text_field :date, class: "form-control", placeholder: 'Enter appointment date' %>
	</div>
	<div class="form-group">
		<%= f.label :description %> <br>
		<%= f.text_field :description, class: "form-control", placeholder: 'Enter desired service' %>
	</div>
	


	<div class="actions">
		<%= f.submit 'Book', class: "btn btn-primary" %>
	</div>
<% end %>

app/views/bookings/index.html.erb
<div id="bookings">
	<h2 style="text-align: center;">Appointments</h2>

	<h2 id="month">
		<%= link_to date: @date.prev_month, class: "btn btn-default" do %>
			<i class="glyphicon glyphicon-chevron-left"></i>
		<% end %>
		<%= @date.strftime("%B %Y") %>
		<%= link_to date: @date.next_month, class: "btn btn-default" do %>
			<i class="glyphicon glyphicon-chevron-right"></i>
		<% end %>
	</h2>
	
	<%# Calendar helper method %>
	<%= calendar @date do |date| %>
		<%= link_to date.day, new_booking_path %>
		<% if @bookings_by_date[date] %>
			<ul>
				<% @bookings_by_date[date].each do |booking| %>
					<li><%= link_to booking.description, booking %></li>
				<% end %>
				
			</ul>
		<% end %>
	<% end %>
</div>

app/views/bookings/new.html.erb
<div class="container" id="appointment">
	<h1><%= @booking.date %></h1>
	<%= render 'form' %>
</div>

app/views/bookings/show.html.erb
<h1><%= @booking.description %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MFMS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Baloo+Da|Candal" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>




	
</head>
<body>

	<nav class="navbar navbar-default" >
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNav" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to 'MFMS', root_path, :class => "navbar-brand" %>
			</div> <!-- /.navbar-header -->
			<div class="collapse navbar-collapse" id="myNav">
					<ul class="nav navbar-nav">
						<li><%= link_to 'About', about_path %></li>
						<li><%= link_to 'Services', services_path %></li>
						<li><%= link_to 'Appointments', bookings_path %></li>
						<li><%= link_to 'Contact', contact_path %></li>
						<% if current_user %>
						 	<li><%= link_to current_user.email %></li>
						 	<li><%= link_to "Log Out", logout_path %></li>
						<% else %>
							<li><%= link_to 'Sign Up', signup_path %></li>
							<li><%= link_to 'Log In', login_path %></li>
						<% end %>
					</ul>
			</div>
			

		</div> <!-- /.container-fluid -->
		
	</nav>
	<% flash.each do |message_type, msg| %>
		<div class="<%= flash_class(message_type) %> fade in">
			<%= msg %>
			<%= link_to "x", nil, { class: "close", :data_dismiss => "alert", :aria_label => "close" } %>
		</div>
	<% end %>

	<%= yield %>


<!--<footer class="site-footer">
	<div class="container">
		<div class="row">
			<div class="col-sm-4">
				<h5>Services</h5>
				<a href="#">Services</a>
			</div>
			<div class="col-sm-4" id="social">
				<h5>Social Media</h5>
				<a href="#">Facebook</a><br>
				<a href="#">Twitter</a><br>	
				<a href="#">Email</a>
			</div>
			<div class="col-sm-4">
				<h5>Contact</h5>
				<p>Phone: 510-860-0755</p>
				<p>Email: mace2300@gmail.com</p>
			</div>
		</div>
	</div>

</footer>-->

</body>
</html>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :location_of_service%><br>
    <%= f.text_field :location_of_service%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<div class="container">
  <div class="row">
    
    <h1 id="serv">Services</h1>

    <% @services.each do |service| %>
    <div class="col-sm-4 col-md-4" id="cols">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= service.name %></h3>
        </div>
        <div class="panel-body">
          <%= image_tag(service.image_url, class: ["images", "img-responsive"] ) %>
        </div>
        <div class="panel-footer">
          <p>
            <%= service.description %>
          </p>
          <p>
            <%= service.location_of_service %>
          </p>
        </div>
      </div>
      
      
      

      <button type="button" class="btn btn-default">
        <%= link_to 'Show', service %>
      </button>
      <button type="button" class="btn btn-default">
        <%= link_to 'Edit', edit_service_path(service) %>
      </button>
      <button type="button" class="btn btn-default">
        <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %>
      </button>
    </div>
    <% end %>
  </div>
</div>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<div class="jumbotron" id="show_page_jumbotron">
	<div class="container">
		<h1><%= @service.name %></h1>
	</div>
</div>


<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @service.image_url %>
</p>

<p>
  <strong>Location of service:</strong>
  <%= @service.location_of_service %>
</p>
<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

app/views/static_pages/about.html.erb
<h2 class="mission">Our Mission</h2>
<h4 class="mission">Keep residents and offices looking prestine!</h4>

<div class="container" id="abt">
	<div class="row">
		<div class="col-sm-12 col-xs-12 w3-card-4">

			<h1>About Us</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum, atque, impedit. Accusantium commodi odit quis voluptatem animi magni, saepe reprehenderit natus exercitationem incidunt in culpa labore voluptatibus quasi, eveniet amet error placeat rerum! Velit quasi assumenda minus necessitatibus, eius doloribus inventore optio, magni, id dolores temporibus fuga cupiditate officiis aliquam. Delectus quas placeat ipsam, eveniet. At doloremque cumque accusamus est doloribus cum consequatur quasi non. Repudiandae distinctio doloribus ipsum dignissimos. Atque praesentium quisquam ex minima aliquam nobis, asperiores suscipit eius, recusandae vel hic. Repellat sunt tempora ipsam dolore aperiam voluptate officiis tempore, amet officia quod ducimus repellendus mollitia rerum vel.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut totam nihil vel eaque eius id. Sequi illo sit asperiores voluptates velit eum voluptatem. Iure cupiditate labore quis eveniet dolores doloremque deserunt provident. Sapiente nesciunt eligendi fuga, illum natus incidunt nulla aut reiciendis doloremque optio delectus magnam quia excepturi culpa sunt labore mollitia ad veniam, nisi harum expedita consectetur ut! Incidunt a quas repellendus molestias, facere. Eos dolorem atque tempora ipsa inventore delectus explicabo reprehenderit incidunt ut vitae, consectetur voluptatem eius tempore provident blanditiis ad, soluta alias. Ducimus vitae doloremque fuga et quae libero, accusamus ratione dolores. Voluptate explicabo suscipit, nihil.</p>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<div class="container" id= "contak">
	<%= form_tag("/static_pages/thank_you") do %>
		<div class="row">
			<div class="col-md-4">
			<h1>Contact Us</h1>
			
				<div class="form-group">
					<%= label_tag :name, "Name" %>
					<%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter full name" %>
				</div>
				<div class="form-group">
					<%= label_tag :email, "Email" %>
					<%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter email address " %>
				</div>
				<div class="form-group">
					<%= label_tag :message, "Message" %>
					<%= text_area_tag :message, nil, class: "form-control", rows: "6", placeholder: "Enter message" %>
				</div>
			</div>
		</div>
			<%= submit_tag "Submit", class: "btn btn-primary" %>
		
	<% end %>
	
</div>

app/views/static_pages/index.html.erb
<%= image_tag("pop_cleans_stairs.jpg", class: "image-responsive pop-stairs") %>

app/views/static_pages/landing_page.html.erb
<div class="jumbotron" id="landing_jumbotron">
	<div class="container">
		<h1>Welcome to Maceo's Facility Maintenance Service</h1>
		<h2>Your number one source for cleaning!</h2>
	</div>
</div>

<div class="container" id="header-info">
	<div class="row">
		<div class="col-sm-4">
			<h3>Reputable business</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure natus cum aperiam fuga error deserunt iste nostrum et amet, id, voluptatibus dignissimos nihil doloremque pariatur ullam a omnis laborum, repudiandae.</p>
		</div>
		<div class="col-sm-4">
			<h3>Quality of work</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure natus cum aperiam fuga error deserunt iste nostrum et amet, id, voluptatibus dignissimos nihil doloremque pariatur ullam a omnis laborum, repudiandae.</p>
		</div>
		<div class="col-sm-4">
			<h3>Green products</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure natus cum aperiam fuga error deserunt iste nostrum et amet, id, voluptatibus dignissimos nihil doloremque pariatur ullam a omnis laborum, repudiandae.</p>
		</div>
	</div>
</div>

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<p>Thank you. We have recieved your message and we will respond as soon as possible.</p>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div class="error_explanantion">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved.</h2>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :email %> <br>
		<%= f.text_field :email, class: "form-control", placeholder: 'jdoe@example.com' %>
	</div>
	<div class="form-group">
		<%= f.label :password %> <br>
		<%= f.password_field :password, class: "form-control", placeholder: 'Minimum 8 characters'%>
	</div>
	<div class="form-group">
		<%= f.label :password_confirmation %> <br>
		<%= f.password_field :password_confirmation, class: "form-control", placeholder: 'Re-enter password' %>
	</div>


	<div class="actions">
		<%= f.submit 'Sign Up', class: "btn btn-primary" %>
	</div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
	<p><%= user.email %></p>
<% end %>

app/views/users/new.html.erb
<div class="container" id="sign-in">
	<h1>Sign up</h1>
	<%= render 'form' %>
</div>